### ISSUE TITLE
ZuulPropertiesRefresher中配置删除问题

### ISSUE THREAD

**Issue by arebya** [ctripcorp/apollo-use-cases#12]
有这样一个case：
如果删除zuul原有的一个route配置，DiscoveryClientRouteLocator中使用的ZuulProperties不会更新，当然handlerMapping中的记录也不会删除。

虽然对业务可能影响很小，但是也算是一个遗留问题。

**Comment by arebya** [comment]
使用RefreshScope也不能很好的解决动态刷新zuul路由配置的问题，RefreshScopeRefreshedEvent会触发eureka client的下线和上线操作，这俩过程是很伤的。

**Comment by nobodyiam** [comment]
看上去是`@ConfigurationProperties`刷新的问题，ZuulProperties中的`routes`只会增加，不会减少。应该可以给Spring Boot提一个issue。

**Comment by arebya** [comment]
相关的issue：
https://github.com/spring-cloud/spring-cloud-netflix/pull/2158
https://github.com/spring-cloud/spring-cloud-netflix/issues/705
以及提出这个问题的人给的一个PR，但是没有被accept
https://github.com/spring-cloud/spring-cloud-commons/pull/234

本issue先关了

**Comment by Jiiiiiin** [comment]
@nobodyiam @arebya 还发现一个问题，就是动态添加的路由映射，不能保证排序，导致不能实现/usr/new/** /usr/** 这样的优先级访问策略问题，不知道是否遇到过这样的问题？

**Comment by Jiiiiiin** [comment]
类似这样的需求  http://blog.didispace.com/spring-cloud-tips-zuul-path-config/

**Comment by nobodyiam** [comment]
@Jiiiiiin 

apollo-client底下的配置会存储在Properties中，而Properties对象继承自Hashtable，所以会导致最终和声明顺序不一致，这块可以考虑下后续是否使用其它实现。

**Comment by nobodyiam** [comment]
@Jiiiiiin see https://github.com/ctripcorp/apollo/pull/2861 https://github.com/ctripcorp/apollo/pull/2912
