### ISSUE TITLE
动态刷新druid数据源实现

### ISSUE THREAD

**Issue by dandanheng** [ctripcorp/apollo-use-cases#24]
模仿示例,写了个druid的动态刷新数据源实现. DataSource更新成功,但查询的时候连接的还是旧数据源.是因为druid的问题吗

**Comment by nobodyiam** [comment]
应该和druid没啥关系，如果实现正确的话，在datasource层就已经换了一个了，建议再debug一下

**Comment by dandanheng** [comment]
谢谢,已经解决,demo里面的刷新bind前缀没有看清.

**Comment by whd120130** [comment]
@dandanheng 大佬有demo 吗？我弄了好久没有成功
