### ISSUE TITLE
针对网关限流和apollo结合实现动态控制相关用例

### ISSUE THREAD

**Issue by Jiiiiiin** [ctripcorp/apollo-use-cases#28]
针对`spring-cloud-zuul-ratelimit`插件的用例：

针对zuul网关限流插件 [marcosbarbero/spring-cloud-zuul-ratelimit](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit)的限流[配置](https://github.com/Jiiiiiin/jiiiiiin-security/blob/feature/springcloud/config/apollo/gateway-server-application.properties#L42)，这边做了一下测试，可以被动态重新加载，[组件在这里](https://github.com/Jiiiiiin/jiiiiiin-security/blob/026e9931f46417c2150c66a4bb1bdf7911a14828/gateway-server/src/main/java/cn/jiiiiiin/zuul/component/apollo/limit/RateLimitPropertiesRefreshConfig.java)

@nobodyiam 是否有添加的意义，麻烦看看 呵呵

**Comment by nobodyiam** [comment]
可以的，欢迎PR！

另外有个小建议，配置监听的时候可以使用interestedKeyPrefixes配置，如@ApolloConfigChangeListener(interestedKeyPrefixes = RateLimitProperties.PREFIX)，会让代码更简单

**Comment by Jiiiiiin** [comment]
好的 谢谢鼓励

**Comment by Jiiiiiin** [comment]
@nobodyiam 已经提交，请大佬帮忙看看 https://github.com/ctripcorp/apollo-use-cases/pull/29

**Comment by Jiiiiiin** [comment]
@nobodyiam 谢谢 学习到了很多pr规范~~
